plugin: aws_ec2
regions:
  - us-east-1   # apna AWS region yahan likho
keyed_groups:
  - key: tags.Name
    prefix: tag_Name_
filters:
  instance-state-name: running
hostnames:
  - private-ip-address
